### ISSUE TITLE
Add TransferType to TransferElement

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#119]
Child of ChimeraTK/ApplicationCore#123

* [ ] Add an enum with TransferType to the TransferElement. It should contain the possible values [read, readNonBlocking, readLatest, readAsync, write, writeDestructively]
* [ ] Add TransferType as an argument to preRead(), postRead(), preWrite(), postWrite() and pass them on to the doPre/Post/Read/Write functions.
* [ ] Add TransferTyp as argument to all the corresponding doPre/Post/Read/Write functions and all of their overloads in DeviceAccess Don't use the new arguments. The current implementations don't need them yet in DeviceAccess (or there are separate tickets for it).
* [ ] Hand the type to preRead(), postRead(), preWrite() and portWrite in the places where they are called. This should  only be in read(), readNonBlocking(), readLatest(), readAsync(), write(), writeDestructively().
* [ ] All the tests should still work, as no functionality has changed. If you have to adapt a test this shows that it is testing implementation details, not functionality. Fix the test accordingly (logically, not by adapting the syntax)
* [ ] Merge to the master
* [ ] Check on Jenkins which projects fail. If there is no ticket for it on the board yet, create them.

Don't try to fix dependent projects in this ticket. This ticket is blocking several other tickets. Create follow-up tickets if they don't exist yet. 

Implements https://chimeratk.github.io/ApplicationCore/master/exception_handling_design.html 3.4. Fixes spec issue 11.22

**Comment by killenb** [comment]
Do before or after #116. Causes an interface change at the same place.
