### ISSUE TITLE
TransferGroup must execute all postReads, even if there are exceptions

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#120]
Child of ChimeraTK/ApplicationCore#123
Depends on #117 

There are two adaptations needed in the TransferGroup
1. The TransferGroup must call readTransfer instead of doReadTransfer
2. postRead() is now throwing. The transfer group is responsible of calling postRead() of ALL its accessors, even if they throw exceptions. The exceptions must be caught and stored, and finally a combined exception message must be created and thrown.

* [ ] Write a test that shows that the behaviour is not implemented at the moment, but would pass if it was
  * Have four accessors from three devices. The "second" and "third" one are from the same device, which should fail
  * Without changes no postRead() will be called because doReadTransfer already throws
  * For a successful test the two "good" accessors should get their values, the exception message should contain two error strings
* [ ] Implement 1 and see that the first postRead() is executed (value arrives in user buffer)
   (This step depends on the order which might not be guaranteed, you may skip the check, which anyway is just visible during development)
* [ ] Implement 2 and the test should pass.

**Comment by phako** [comment]
I'm not sure if this is a bug in the ExceptionDummyDevice after #117 or a generic issue:

When I set the dummy device to throw an exception on reads, the following happens:

-  the readTransfer() on the lowLevel element sets the "hasSeenException" flag to true
- he postRead() happens on the highLevel element. This does not have the hasSeenException flag set, so no exception is bubbling up and everything is happy

There's is a preliminary test in wip-phako-120-execute-all-the-postreads, currently modified for debugging purposes

**Comment by killenb** [comment]
I guess this is a side effect of #116 not being implemented yet. It was blocked by #119 until now. I did not see that it would also affect #120

**Comment by phako** [comment]
Not sure. I hacked in the changes in #116 to always call `postRead()` but the behavior does not change.

**Comment by phako** [comment]
I think the implementation of 3.1 is missing, in combination with TransferGroup splitting the transfer between HL/LL accessors itself. exceptions shoiuld only be thrown in doPost(Read|Write). Currently the exception is thrown in postRead() which is never called on the hardware accessing element, and wouldn't do anyting, because it does not know it is in a transfer transaction, because the transfer group also does not call preRead() on it.

**Comment by killenb** [comment]
That preRead/Write is not called is a bug. preReadWrite and postRead/Write must always be called in pairs.

To change the calls from doReadTransfer() to readTransfer() actually is the first task of this ticket.

**Comment by phako** [comment]
the half-sentence with the doPost... should have come after 3.1 as the contents of that section. The TransferGroup is not calling doPost..()

**Comment by killenb** [comment]
I will check and adapt the spec, thanks
