### ISSUE TITLE
Implement interrupts in PCIe device backend

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DeviceAccess#78]
This ticket depends on several others:

* interrupt feature in the driver (ChimeraTK/pcieuni-driver#2)
* interrupt description in the map file (#74)
* AsyncNDRegisterAccessor (#76)

After the ingredients are there, the PCIe backend can be extended to deliver the "user space interrupts" coming from the blocking ioctl as push-type registers. The pcie backend will either be or have a SubscriptionManager for AsyncNDRegisterAccessors. The accessor which is handed out is an AsyncNDRegisterAccessor which is registered to it.
The backend will have a dispatcher thread which is waiting for the blocking ioctl from the driver. After having received data it is sending the "interrupts" to all registered accessors.
When implementing this make sure that the ioctl is interruptible so the application can be shut down cleanly. Make sure to have shutdown() adapted correctly.

There are two possible descriptions in the map file:
1. One variable that contains all interrupts as bit pattern. There only is one push-type variabler if this is used exclusively, but each registered accessor has a FutureQueue, so they all must be fed with the data. Start with this implementation.
2. One (void) variable per interrupts (bit in the multi-interrupt word). The dispatcher thread does the bit interpretation and only sends data to the variables that are waiting for the particular interrupts.

There should be unit tests for this feature. To implement it, the pciedummy driver needs to be extended (ChimeraTK/pciedummy-driver#5)

Definition of done:
* [ ] The feature is working for one word with all interrupts to be interpreted by the application (automated unit test and real hardware)
* [ ] The feature is working for void-type registers just waiting for a single interrupt (automated unit test and read hardware)
* [ ] There is documentation how to use the feature

**Comment by killenb** [comment]
This ticket has been moved to the DESY MSK request tracker https://redmine.msktools.desy.de/issues/7871 (sorry, DESY internal access only).
